name: Build Go binaries

on:
  push:
    # We want to run the workflow on all branches.
    # But you can restrict the runs if necessary.
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Make binaries
        uses: cyd01/actions/golang-build@master
        # Uncomment to following piece to restrict targets
        # with:
        #   args: linux/amd64 darwin/amd64

      - name: Upload artefacts
        uses: actions/upload-artifact@v2
        with:
          name: releases
          path: ${{ github.workspace }}/.release
